FAT2-371 remove fatv1 api
SkillsFundingAgency/das-assessor-service pull request #1113
Opened 2021-01-28 08:03 UTC by dashton82

This removes FATv1 from the assessor service. Due to large amounts of change occurring as a result of the work the Standards Versioning (SV) team are doing. Only the call for Standards Collation has been modified to use the assessor outer api. This will eventually change further as the SV project progresses. The call that was being done to check a provider name has also been replaced to call RoATP directly for now. This will ultimately be replaced with the work SV team are doing.

2021-01-28 09:37 UTC, dashton82 commented
The sonar fail is due to me touching an existing set of handlers that were already pretty much a CTRL C, CTRL V from one an other.....

2021-01-28 10:14 UTC, ChrisJWoodcock requested changes

2021-01-28 10:14 UTC, ChrisJWoodcock commented on src/SFA.DAS.AssessorService.Application/Infrastructure/OuterApi/ApiClient.cs
> +        Task<TResponse> Get<TResponse>(IGetApiRequest getStandardsRequest);
The name should be request

2021-01-28 10:29 UTC, ChrisJWoodcock submitted a review, later dismissed

2021-01-28 14:33 UTC, scottywakefield approved these changes

2021-01-28 16:40 UTC, dashton82 commented on src/SFA.DAS.AssessorService.Application/Infrastructure/OuterApi/ApiClient.cs
> +        Task<TResponse> Get<TResponse>(IGetApiRequest getStandardsRequest);
all resolved now

2021-02-12 10:05 UTC, ChrisJWoodcock approved these changes

2021-02-12 10:25 UTC, merged