SV-1305 Expired Financial Stage 1
SkillsFundingAgency/das-assessor-service pull request #1376
Opened 2021-11-15 17:47 UTC by techtoniq

2021-11-16 13:32 UTC, alandburns requested changes
If I am reading this right, it is not taking account of when the Organisation has been marked as being Exempt from Financial review and hence will not be required to (re)do a financial review, but this does not essentially mean that the financial due date does not have an out of date value.
You cannot rely solely on a null "FinancialDueDate" value.

2021-11-16 14:46 UTC, techtoniq commented
Per discussion with Al - DO NOT MERGE. Awaiting confirmation on the business process/comms required where the data does not have a value for the "FinancialExempt" flag.

2021-11-29 14:27 UTC, CodeWolf86 approved these changes

2021-11-30 09:15 UTC, CodeWolf86 requested changes

2021-11-30 09:15 UTC, CodeWolf86 commented on src/SFA.DAS.AssessorService.Application/Helpers/FinancialReviewStatusHelper.cs
> +    public static class FinancialReviewStatusHelper
Could we get some unit tests around confirming the behaviour of when you are financially exempt?

2021-12-06 09:24 UTC, CodeWolf86 approved these changes

2021-12-06 09:24 UTC, merged