SV-1350-SQL Tweaks for StaffSearch
SkillsFundingAgency/das-assessor-service pull request #1394
Opened 2021-12-21 11:16 UTC by CodeWolf86

2021-12-21 16:56 UTC, cofaulco approved these changes

2022-01-04 09:41 UTC, ChrisJWoodcock requested changes
The new index on the certificates table only includes the computed fields - I think that it should be containing the primary key as well so that the index can be used to refer to the other data?

2022-01-04 09:42 UTC, ChrisJWoodcock requested changes
There is no index on the new computed column in the learner table - so that would not make a different to the performance

2022-01-05 10:26 UTC, CodeWolf86 commented
> The new index on the certificates table only includes the computed fields - I think that it should be containing the primary key as well so that the index can be used to refer to the other data?

I was working on the basis that at minimum, if the Index has the same fields in it as the where clause it can make use of it as part of the query. But I take your point that having the ID in there as well can make a difference when connecting up to various related data.

2022-01-05 10:41 UTC, ChrisJWoodcock submitted a review, later dismissed

2022-01-05 11:07 UTC, ChrisJWoodcock approved these changes

2022-01-11 09:44 UTC, merged