net 8.0 ugradeP2-1768-Net8_upgrade
SkillsFundingAgency/das-assessor-service pull request #1628
Opened 2024-10-21 15:13 UTC by karen-hanna

2024-11-21 09:23 UTC, ChrisJWoodcock requested changes

2024-11-21 12:15 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/SFA.DAS.AssessorService.Application.csproj
> +    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
Moved to transient reference section

2024-11-21 12:21 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AutoMapperExtensions.cs
> +        public static IMappingExpression<TSource, TDestination> IgnoreAll<TSource, TDestination>(
I have created a new project for the shared extension.  I have removed the previous methods and replaced them with IgnoreUnmappedMembers - which loops through the mappings and marks any unmatched members as Ignore.

2024-11-21 12:21 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/AutoMapperExtensions.cs
> +    public static class AutoMapperExtensions
I have created a new project for the shared extension.  I have removed the previous methods and replaced them with IgnoreUnmappedMembers - which loops through the mappings and marks any unmatched members as Ignore.

2024-11-21 12:28 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AssessorServiceOrganisationProfile.cs
> +                .MapMatchingMembersAndIgnoreOthers();
It was all a bit messy.  I have created an IgnoreUnmappedMembers extension method which is used by all 3 projects.  Automapper still maps matching properties as before so i can remove any references to matching.  And the IgnoreUnmappedMembers looks like this :

`public static IMappingExpression<TSource, TDestination> IgnoreUnmappedMembers<TSource, TDestination>(
    this IMappingExpression<TSource, TDestination> mappingExpression)
{
    var sourceProperties = typeof(TSource).GetProperties(BindingFlags.Public | BindingFlags.Instance);
    var destinationProperties = typeof(TDestination).GetProperties(BindingFlags.Public | BindingFlags.Instance);

    var sourcePropertyNames = new HashSet<string>(sourceProperties.Select(p => p.Name));

    foreach (var destinationProperty in destinationProperties)
    {
        if (!sourcePropertyNames.Contains(destinationProperty.Name))
        {
            mappingExpression.ForMember(destinationProperty.Name, opt => opt.Ignore());
        }
    }
    return mappingExpression;
}`

2024-11-21 12:29 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/AutoMapperExtensions.cs
> +            var matchingProperties = new HashSet<string>(sourceProperties.Select(p => p.Name));
Resolved with new method in shared library

2024-11-21 12:30 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/AutoMapperExtensions.cs
> +    public static class AutoMapperExtensions
The whole Autompper change was a procvessw, which was not very effective!!  I have now created an IgnoreUnmappedMembers method which is more accurate.  The automapping bit is still done by automapper

2024-11-21 12:31 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AutoMapperExtensions.cs
> +        public static IMappingExpression<TSource, TDestination> IgnoreAll<TSource, TDestination>(
Covered in other comments, should be resolved

2024-11-21 16:27 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/SFA.DAS.AssessorService.Application.Api.csproj
> +    <ProjectReference Include="..\SFA.DAS.AssessorService.Application.Api.External\SFA.DAS.AssessorService.Application.Api.External.csproj" />
removed

2024-11-21 16:36 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/AutoMapperExtensions.cs
> +﻿using AutoMapper;
removed

2024-11-21 16:45 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/Mapping/AutoMapperProfiles/EpaOrganisationProfile.cs
> +                .MapMatchingMembersAndIgnoreOthers()
Automapper will map those that match directy, so the ones I have removed are picked up by the base functionality.  I verified this by writing a debug method to inspect the loaded mappings and was able to print the mapped/ignored members : 
Ignored Properties for mapping EpaOrganisation -> UpdateEpaOrganisationRequest:
  - ActionChoice
Mapped Properties for mapping EpaOrganisation -> UpdateEpaOrganisationRequest:
  - Name
  - **OrganisationId**
  - **Ukprn**
  - **OrganisationTypeId**
  - **Status**
  - RecognitionNumber
  - LegalName
  - TradingName
  - ProviderName
  - Email
  - PhoneNumber
  - WebsiteLink
  - Address1
  - Address2
  - Address3
  - Address4
  - Postcode
  - CompanyNumber
  - CompanySummary
  - CharityNumber
  - CharitySummary
  - FinancialDueDate
  - FinancialExempt

2024-11-21 16:48 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/AutoMapperExtensions.cs
> +            var matchingProperties = new HashSet<string>(sourceProperties.Select(p => p.Name));
updated and moved to shared method

2024-11-21 16:49 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AssessorServiceOrganisationProfile.cs
> +                .MapMatchingMembersAndIgnoreOthers();
Automapper will automatically map matching members, so we dont need to code for these.  And i have added a new method to ignore unmapped members only

2024-11-27 12:34 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/MappingStartup.cs
> -
Profiles are automatically detected by Automapper.  I have created AutoMapAnalyser to find the loaded mapping and compare them with all mapping calls in the code to ensure everything is covered.

2024-11-27 12:36 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
> +                services.AddTransient<IDateTimeHelper, DateTimeHelper>();
moved to helper method

2024-11-27 12:37 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.UnitTests/SFA.DAS.AssessorService.Application.UnitTests.csproj
> +    <ProjectReference Include="..\SFA.DAS.AssessorService.Application.Api\SFA.DAS.AssessorService.Application.Api.csproj" />
removed

2024-11-27 12:41 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
> +            var a = _mapper.Map<List<SearchResult>>(learnerResults);
updated

2024-11-27 12:51 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/Mapping/AutoMapperProfiles/ApplicationResponseProfile.cs
> +                .MapMatchingMembersAndIgnoreOthers()
Most will be automapped, but you are right and I have added ContactName and ContactEmail.  Whwen i runt he analyser i can see that all previously listed fields are mapped 

Mapped Properties for mapping ApplySummary -> ApplicationResponse:
  - Id
  - ApplicationId
  - StandardApplicationType
  - OrganisationId
  - EndPointAssessorName
  - FinancialGrade
  - ApplicationStatus
  - ReviewStatus
  - FinancialReviewStatus
  - ApplyData
  - StandardCode
  - StandardReference
  - ApplyViaOptIn
  - CreatedBy
  - ApplicationType
  - ContactName
  - ContactEmail

2024-11-27 12:53 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application/SFA.DAS.AssessorService.Application.csproj
> +    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
moved to transient reference section

2024-11-27 13:58 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Web/Startup.cs
moved to extension method

2024-12-04 16:15 UTC, karen-hanna commented on src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/ServiceCollectionExtensions.cs
> +    public static class ServiceCollectionExtensions
done

2024-12-06 14:52 UTC, ChrisJWoodcock submitted a review, later dismissed

2025-01-27 14:41 UTC, debrr07 approved these changes

2025-01-27 16:29 UTC, ChrisJWoodcock approved these changes

2025-01-27 16:30 UTC, merged